use bevy::{ecs::resource::Resource, log::info};
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::sync::Arc;

use crate::items::{InventorySlot, ItemConfig, ItemFlag, ItemId};

#[derive(Resource, Debug)]
pub struct ItemConfigs {
    pub items: HashMap<ItemId, Arc<ItemConfig>>,
}

pub fn read_item_configs() -> HashMap<ItemId, Arc<ItemConfig>> {
    let Ok(contents) = fs::read_to_string("assets/configs/items.json") else {
        panic!("Could not read items file");
    };
    let item_configs: Value = serde_json::from_str(&contents).unwrap();
    let mut item_map: HashMap<ItemId, Arc<ItemConfig>> = HashMap::new();
    for conf in item_configs.as_array().unwrap().iter() {
        if let Some(item) = read_item_config(conf) {
            item_map.insert(item.id, item);
        } else {
            panic!("Could not read items file");
        }
    }

    item_map
}

fn read_item_config(config: &Value) -> Option<Arc<ItemConfig>> {
    let id = config["id"].as_u64()? as ItemId;
    let minimap_color = config["minimap_color"].as_u64().map(|v| v as u8);
    // Only ground items carry friction, mirroring the server's data invariant that
    // `tile_friction` appears on exactly its ground items and nothing else. Without
    // the condition every item would hold `Some(0)` and `get_tile_friction`'s
    // "first item with a value" rule would resolve to the bottom of the stack.
    //
    // A ground item with no readable `ground_speed` fails the whole parse rather
    // than defaulting: friction 0 is a legitimate value, so a silent default would
    // be indistinguishable from a frictionless tile and would surface as mispaced
    // movement rather than as a startup error.
    let friction = if config["is_ground"].as_bool().unwrap_or(false) {
        Some(config["ground_speed"].as_u64()? as u16)
    } else {
        None
    };
    let slot = if config["slot"].is_null() {
        None
    } else {
        Some(match config["slot"].as_u64()? {
            0 => InventorySlot::BothHands,
            1 => InventorySlot::Head,
            2 => InventorySlot::Amulet,
            3 => InventorySlot::Backpack,
            4 => InventorySlot::Chest,
            5 => InventorySlot::RightHand,
            6 => InventorySlot::LeftHand,
            7 => InventorySlot::Legs,
            8 => InventorySlot::Feet,
            9 => InventorySlot::Ring,
            10 => InventorySlot::Trinket,
            _ => {
                info!("{:?}", config);
                return None;
            }
        })
    };
    let elevation = if config["elevation"].is_null() {
        None
    } else {
        Some(config["elevation"].as_u64()? as u8)
    };
    let mut flags: Vec<ItemFlag> = Vec::new();
    if config["is_ground"].as_bool()? {
        flags.push(ItemFlag::Ground);
    }
    if config["is_border"].as_bool()? {
        flags.push(ItemFlag::Border);
    }
    if !config["can_walk"].as_bool()? {
        flags.push(ItemFlag::Unpass);
    }
    if config["fullbank"].as_bool()? {
        flags.push(ItemFlag::FullBank);
    }
    if config["top"].as_bool()? {
        flags.push(ItemFlag::Top);
    }
    if config["is_container"].as_bool()? {
        flags.push(ItemFlag::Container);
    }
    if !config["can_move"].as_bool()? {
        flags.push(ItemFlag::Unmove);
    }
    if config["cumulative"].as_bool()? {
        flags.push(ItemFlag::Cumulative);
    }
    if config["can_take"].as_bool()? {
        flags.push(ItemFlag::Take);
    }
    if config["bottom"].as_bool()? {
        flags.push(ItemFlag::Bottom);
    }
    if config["usable"].as_bool()? {
        flags.push(ItemFlag::Usable);
    }
    if config["avoid"].as_bool()? {
        flags.push(ItemFlag::Avoid);
    }
    if config["lying_object"].as_bool()? {
        flags.push(ItemFlag::LyingObject);
    }
    if config["block_sight"].as_bool()? {
        flags.push(ItemFlag::BlockSight);
    }
    if config["multiuse"].as_bool()? {
        flags.push(ItemFlag::MultiUse);
    }
    if config["forceuse"].as_bool()? {
        flags.push(ItemFlag::ForceUse);
    }
    // Read with `?` like every other flag, so an items.json regenerated by a
    // generator that has dropped these fields panics at startup instead of
    // silently deciding no item in the game is a liquid.
    if config["liquid_pool"].as_bool()? {
        flags.push(ItemFlag::LiquidPool);
    }
    if config["liquid_container"].as_bool()? {
        flags.push(ItemFlag::LiquidContainer);
    }
    Some(Arc::new(ItemConfig {
        id,
        // name,
        flags,
        friction,
        slot,
        minimap_color,
        elevation,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Every field `read_item_config` reads with `?` before it ever reaches the
    /// friction line, filled with a value that satisfies its type. Individual
    /// tests only vary `is_ground` and `ground_speed` -- the two fields the
    /// friction gate depends on -- so a test failing there means friction, not an
    /// incomplete fixture.
    fn item_json(is_ground: bool, ground_speed: Value) -> Value {
        json!({
            "id": 1,
            "minimap_color": 0,
            "is_ground": is_ground,
            "ground_speed": ground_speed,
            "slot": null,
            "elevation": null,
            "is_border": false,
            "can_walk": true,
            "fullbank": false,
            "top": false,
            "is_container": false,
            "can_move": true,
            "cumulative": false,
            "can_take": false,
            "bottom": false,
            "usable": false,
            "avoid": false,
            "block_sight": false,
            "multiuse": false,
            "forceuse": false,
            "liquid_pool": false,
            "liquid_container": false,
            "lying_object": false,
        })
    }

    /// A plain ground item carries its ground_speed through as friction.
    #[test]
    fn ground_item_with_a_ground_speed_carries_that_friction() {
        let config = item_json(true, json!(100));

        let item = read_item_config(&config)
            .expect("fixture supplies every field read_item_config requires");

        assert_eq!(item.friction, Some(100));
    }

    /// Friction widened to u16 in cdedde9 specifically so values above u8::MAX
    /// (255) survive the parse. `ornamented stone floor` (id 21718) is the real
    /// asset that motivated it, with a ground_speed of 260.
    #[test]
    fn ground_item_with_friction_above_255_keeps_the_full_value() {
        let config = item_json(true, json!(260));

        let item = read_item_config(&config)
            .expect("fixture supplies every field read_item_config requires");

        assert_eq!(item.friction, Some(260));
    }

    /// `Map::get_tile_friction` resolves a tile's friction by taking the first
    /// item in the stack that carries a value, relying on non-ground items never
    /// carrying one -- even when their raw ground_speed happens to be present and
    /// zero, as it may be for items that were never meant to report friction.
    #[test]
    fn non_ground_item_has_no_friction_even_with_a_zero_ground_speed() {
        let config = item_json(false, json!(0));

        let item = read_item_config(&config)
            .expect("fixture supplies every field read_item_config requires");

        assert_eq!(item.friction, None);
    }

    /// A ground item's ground_speed missing from the source data must fail the
    /// whole parse (propagating via `?`) rather than silently default to friction
    /// 0, which is itself a legitimate value and would be indistinguishable from a
    /// real frictionless tile at runtime.
    #[test]
    fn ground_item_missing_ground_speed_fails_the_parse() {
        let mut config = item_json(true, json!(0));
        config
            .as_object_mut()
            .expect("item_json builds an object")
            .remove("ground_speed");

        assert!(read_item_config(&config).is_none());
    }

    /// Same failure mode as the missing-field case, but for corrupted source data
    /// where `ground_speed` is present with the wrong type. `as_u64()` returns
    /// `None` here exactly as it does for a missing key, so the same fail-loud
    /// path covers both.
    #[test]
    fn ground_item_with_non_numeric_ground_speed_fails_the_parse() {
        let config = item_json(true, json!("fast"));

        assert!(read_item_config(&config).is_none());
    }
}
